In [52]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [53]:
df=pd.read_csv('/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [54]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [58]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [59]:
df.drop(columns=["RowNumber","CustomerId","Surname"],inplace=True)

In [60]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [61]:
df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [62]:
df=df.astype(int)

In [63]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0,1,1,1,101348,1,0,0,0
1,608,41,1,83807,1,0,1,112542,0,0,1,0
2,502,42,8,159660,3,1,0,113931,1,0,0,0
3,699,39,1,0,2,0,0,93826,0,0,0,0
4,850,43,2,125510,1,1,1,79084,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0,2,1,0,96270,0,0,0,1
9996,516,35,10,57369,1,1,1,101699,0,0,0,1
9997,709,36,7,0,1,0,1,42085,1,0,0,0
9998,772,42,3,75075,2,1,0,92888,1,1,0,1
9999,792,28,4,130142,1,1,0,38190,0,0,0,0

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
X=df.drop(columns=['Exited'])
y=df['Exited']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [66]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [75]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [76]:
model=Sequential()
model.add(Dense(3,activation='sigmoid',input_dim=11))#input layer me 3 node hai and 11 inputs ie columns 11*3 weight +3 biases
model.add(Dense(1,activation='sigmoid'))#output layer me 1 layer 3*1 weights + 1 bias

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-03-25 17:21:00.693326: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [77]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [78]:
#complie the model
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [80]:
model.fit(X_train_scaled,y_train,epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5367
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4955
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4784
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4589
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4487
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4333
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4263
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4330
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4331
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4305

In [81]:
model.layers[0].get_weights()#we get 33 weights and 3 bias

[array([[ 0.22191451,  0.13167123, -0.06921893],
        [-1.2436427 , -0.6148416 , -2.4733946 ],
        [-0.11463722,  0.19732633,  0.12815882],
        [ 0.00788508, -0.40817502, -0.18340325],
        [ 0.13700132, -0.01468947,  0.10581943],
        [-0.1442326 ,  0.18534797,  0.03075132],
        [ 0.3424775 ,  0.9045108 ,  0.19123305],
        [ 0.04347471, -0.1584281 , -0.07755303],
        [-0.3367966 , -0.8413887 , -0.11767127],
        [-0.02585156, -0.17649902,  0.37977788],
        [ 0.6077463 ,  0.37200072,  0.14840251]], dtype=float32),
 array([-0.03975134, -0.01059319,  0.17084901], dtype=float32)]

In [82]:
model.layers[1].get_weights()

[array([[-1.1088939],
        [-1.4999577],
        [-0.9490192]], dtype=float32),
 array([0.20098422], dtype=float32)]

In [84]:
y_log=model.predict(X_test_scaled)
#if >0.5 then 1 else 0

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [85]:
np.where(y_log>0.5,1,0)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [86]:
y_pred=np.where(y_log>0.5,1,0)

In [87]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.818

In [88]:
model=Sequential()
model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid'))#output layer me 1 layer 3*1 weights + 1 bias

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [89]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [91]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])#loss ke sath ab accuracy be dikhaye ga

In [94]:
model.fit(X_train_scaled,y_train,epochs=100,validation_split=0.2)#validation_split=0.2 use to train+test 20 percent of training data ie to get validation

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8665 - loss: 0.3141 - val_accuracy: 0.8662 - val_loss: 0.3425
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8651 - loss: 0.3225 - val_accuracy: 0.8662 - val_loss: 0.3419
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8706 - loss: 0.3183 - val_accuracy: 0.8662 - val_loss: 0.3435
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8687 - loss: 0.3132 - val_accuracy: 0.8694 - val_loss: 0.3418
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8740 - loss: 0.3090 - val_accuracy: 0.8637 - val_loss: 0.3454
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8700 - loss: 0.3168 - val_accuracy: 0.8681 - val_loss: 0.3423
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8720 - loss: 0.3097 - val_accuracy: 0.8669 - val_loss: 0.3451
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8616 - loss: 0.3245 - val_accuracy: 0.8669 - val_loss: 0.3413
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8635 - loss: 0.3206 - val_accuracy: 0.8631 - val_loss: 0.3450
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8636 - loss: 0.3222 - val_accuracy: 0.8612 - val_loss: 0.3464
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8590 - loss: 0.3298 - val_accuracy: 0.8662 - val_loss: 0.3422
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8678 - loss: 0.3141 - val_accuracy: 0.8681 - val_loss: 0.3414
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8605 - loss: 0.3280 - val_accuracy: 0.8625 - val_loss: 0.3438
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8699 - loss: 0.3151 - val_accuracy: 0.8662 - val_loss: 0.3432
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8605 - loss: 0.3228 - val_accuracy: 0.8681 - val_loss: 0.3448
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8630 - loss: 0.3265 - val_accuracy: 0.8669 - val_loss: 0.3441
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8693 - loss: 0.3187 - val_accuracy: 0.8656 - val_loss: 0.3434
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8642 - loss: 0.3203 - val_accuracy: 0.8662 - val_loss: 0.3410
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8714 - loss: 0.3109 - val_accuracy: 0.8631 - val_loss: 0.3457
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8606 - loss: 0.3312 - val_accuracy: 0.8650 - val_loss: 0.3443
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8694 - loss: 0.3122 - val_accuracy: 0.8650 - val_loss: 0.3455
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8694 - loss: 0.3153 - val_accuracy: 0.8631 - val_loss: 0.3469
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8583 - loss: 0.3335 - val_accuracy: 0.8644 - val_loss: 0.3424
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8699 - loss: 0.3117 - val_accuracy: 0.8637 - val_loss: 0.3456
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8605 - loss: 0.3291 - val_accuracy: 0.8650 - val_loss: 0.3427
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8564 - loss: 0.3316 - val_accuracy: 0.8656 - val_loss: 0.3430
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8627 - loss: 0.3271 - val_accuracy: 0.8656 - val_loss: 0.3443
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8672 - loss: 0.3216 - val_accuracy: 0.8662 - val_loss: 0.3441
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8628 - loss: 0.3248 - val_accuracy: 0.8631 - val_loss: 0.3464
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8661 - loss: 0.3210 - val_accuracy: 0.8606 - val_loss: 0.3452
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8646 - loss: 0.3183 - val_accuracy: 0.8650 - val_loss: 0.3464
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8594 - loss: 0.3247 - val_accuracy: 0.8650 - val_loss: 0.3449
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8605 - loss: 0.3239 - val_accuracy: 0.8687 - val_loss: 0.3425
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8648 - loss: 0.3212 - val_accuracy: 0.8644 - val_loss: 0.3451
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8667 - loss: 0.3149 - val_accuracy: 0.8656 - val_loss: 0.3446
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8667 - loss: 0.3214 - val_accuracy: 0.8662 - val_loss: 0.3431
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8660 - loss: 0.3209 - val_accuracy: 0.8650 - val_loss: 0.3428
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8585 - loss: 0.3363 - val_accuracy: 0.8662 - val_loss: 0.3431
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8676 - loss: 0.3160 - val_accuracy: 0.8631 - val_loss: 0.3483
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8613 - loss: 0.3280 - val_accuracy: 0.8644 - val_loss: 0.3433
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8585 - loss: 0.3282 - val_accuracy: 0.8631 - val_loss: 0.3442
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8671 - loss: 0.3207 - val_accuracy: 0.8669 - val_loss: 0.3437
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8645 - loss: 0.3143 - val_accuracy: 0.8644 - val_loss: 0.3462
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8632 - loss: 0.3210 - val_accuracy: 0.8656 - val_loss: 0.3431
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8626 - loss: 0.3291 - val_accuracy: 0.8637 - val_loss: 0.3454
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8712 - loss: 0.3124 - val_accuracy: 0.8612 - val_loss: 0.3471
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8671 - loss: 0.3163 - val_accuracy: 0.8675 - val_loss: 0.3415
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8651 - loss: 0.3158 - val_accuracy: 0.8637 - val_loss: 0.3428
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8647 - loss: 0.3151 - val_accuracy: 0.8637 - val_loss: 0.3444
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8628 - loss: 0.3272 - val_accuracy: 0.8637 - val_loss: 0.3429
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8692 - loss: 0.3161 - val_accuracy: 0.8625 - val_loss: 0.3481
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8639 - loss: 0.3142 - val_accuracy: 0.8650 - val_loss: 0.3432
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8661 - loss: 0.3168 - val_accuracy: 0.8656 - val_loss: 0.3446
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8699 - loss: 0.3225 - val_accuracy: 0.8637 - val_loss: 0.3431
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8661 - loss: 0.3170 - val_accuracy: 0.8637 - val_loss: 0.3431
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8654 - loss: 0.3237 - val_accuracy: 0.8619 - val_loss: 0.3449
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8669 - loss: 0.3187 - val_accuracy: 0.8644 - val_loss: 0.3420
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8668 - loss: 0.3082 - val_accuracy: 0.8619 - val_loss: 0.3464
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8740 - loss: 0.3072 - val_accuracy: 0.8637 - val_loss: 0.3419
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8681 - loss: 0.3220 - val_accuracy: 0.8625 - val_loss: 0.3434
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8620 - loss: 0.3215 - val_accuracy: 0.8612 - val_loss: 0.3454
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8646 - loss: 0.3190 - val_accuracy: 0.8619 - val_loss: 0.3470
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8708 - loss: 0.3136 - val_accuracy: 0.8612 - val_loss: 0.3455
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8621 - loss: 0.3158 - val_accuracy: 0.8669 - val_loss: 0.3436
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8676 - loss: 0.3059 - val_accuracy: 0.8631 - val_loss: 0.3420
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8680 - loss: 0.3151 - val_accuracy: 0.8606 - val_loss: 0.3441
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8731 - loss: 0.3050 - val_accuracy: 0.8619 - val_loss: 0.3462
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8620 - loss: 0.3278 - val_accuracy: 0.8612 - val_loss: 0.3434
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8687 - loss: 0.3170 - val_accuracy: 0.8631 - val_loss: 0.3415
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8689 - loss: 0.3177 - val_accuracy: 0.8631 - val_loss: 0.3467
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8617 - loss: 0.3184 - val_accuracy: 0.8619 - val_loss: 0.3431
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8661 - loss: 0.3235 - val_accuracy: 0.8637 - val_loss: 0.3424
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8757 - loss: 0.3053 - val_accuracy: 0.8637 - val_loss: 0.3416
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8674 - loss: 0.3104 - val_accuracy: 0.8637 - val_loss: 0.3421
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8632 - loss: 0.3167 - val_accuracy: 0.8631 - val_loss: 0.3468
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8653 - loss: 0.3226 - val_accuracy: 0.8656 - val_loss: 0.3415
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.3183 - val_accuracy: 0.8612 - val_loss: 0.3467
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8663 - loss: 0.3186 - val_accuracy: 0.8637 - val_loss: 0.3426
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8635 - loss: 0.3260 - val_accuracy: 0.8637 - val_loss: 0.3428
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8618 - loss: 0.3259 - val_accuracy: 0.8625 - val_loss: 0.3452
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8644 - loss: 0.3212 - val_accuracy: 0.8625 - val_loss: 0.3434
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8743 - loss: 0.3018 - val_accuracy: 0.8600 - val_loss: 0.3442
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8575 - loss: 0.3360 - val_accuracy: 0.8631 - val_loss: 0.3453
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8687 - loss: 0.3136 - val_accuracy: 0.8619 - val_loss: 0.3481
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8725 - loss: 0.3049 - val_accuracy: 0.8644 - val_loss: 0.3443
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8650 - loss: 0.3206 - val_accuracy: 0.8612 - val_loss: 0.3454
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8629 - loss: 0.3189 - val_accuracy: 0.8619 - val_loss: 0.3430
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8730 - loss: 0.3127 - val_accuracy: 0.8575 - val_loss: 0.3459
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8653 - loss: 0.3194 - val_accuracy: 0.8612 - val_loss: 0.3442
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8704 - loss: 0.3083 - val_accuracy: 0.8637 - val_loss: 0.3464
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8687 - loss: 0.3133 - val_accuracy: 0.8594 - val_loss: 0.3451
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8609 - loss: 0.3201 - val_accuracy: 0.8625 - val_loss: 0.3453
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8648 - loss: 0.3133 - val_accuracy: 0.8625 - val_loss: 0.3415
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8659 - loss: 0.3141 - val_accuracy: 0.8619 - val_loss: 0.3443
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3272 - val_accuracy: 0.8619 - val_loss: 0.3444
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8658 - loss: 0.3162 - val_accuracy: 0.8631 - val_loss: 0.3420
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8677 - loss: 0.3087 - val_accuracy: 0.8606 - val_loss: 0.3420
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8664 - loss: 0.3165 - val_accuracy: 0.8631 - val_loss: 0.3419
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8691 - loss: 0.3131 - val_accuracy: 0.8637 - val_loss: 0.3427
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8615 - loss: 0.3210 - val_accuracy: 0.8644 - val_loss: 0.3421

In [96]:
model.layers[1].get_weights()

[array([[-0.24002981, -0.05478832,  0.2426592 ,  0.08179129, -1.0427231 ,
          0.1646812 , -0.77326584, -0.8212498 , -0.09067717,  0.3810334 ,
         -0.24227731],
        [ 0.02351191,  0.46703455,  0.2651656 ,  0.30694094, -0.1391051 ,
         -0.19286868, -0.9476555 ,  0.22712053, -0.45732304,  0.61801106,
         -0.02010183],
        [ 0.24818641, -0.07062621,  0.10508379, -0.13973553, -0.00864702,
          0.08396944,  0.80627346,  0.1560978 ,  0.21954332, -0.48612136,
          0.24483052],
        [-0.00689135, -0.26796147,  0.4487552 ,  0.05658541, -0.7352628 ,
         -0.65414625, -0.5228453 , -0.28450847,  0.6455454 , -0.70147485,
         -0.3750665 ],
        [-0.12591249,  0.13930948, -0.7247986 , -0.82914567, -0.01477153,
         -0.87820894,  0.3446017 ,  0.89028776, -0.08271714,  0.39009225,
         -0.29353404],
        [-0.38701612,  0.2826797 ,  0.25530806, -0.3173833 , -0.47651243,
         -0.57913464,  0.27646017,  0.10210671, -0.26306984,  0.3854311 ,
         -0.23743215],
        [ 1.1305507 ,  0.17225935, -0.19800462,  0.22854118,  0.5599629 ,
          0.58474374,  0.10900145,  0.11070291, -1.7531272 , -0.2525551 ,
          0.6794185 ],
        [ 0.22380115,  0.2947211 ,  0.09765199, -0.714168  ,  0.20453951,
         -0.8694472 ,  0.41505602,  0.7043768 , -0.32344097,  0.6225419 ,
          0.6995043 ],
        [ 0.14078836, -0.36485547, -0.55234003, -0.26644018, -0.77764195,
         -0.7278195 , -0.7162397 , -0.04409944, -0.27569014, -0.12102629,
         -0.18633938],
        [ 0.4578862 , -0.17547394, -0.34825045, -0.5834979 ,  0.542311  ,
          0.59962493, -0.27339584, -0.7650907 , -0.68210495, -0.06051901,
          0.6750359 ],
        [ 0.03594683,  0.12503605,  0.7266932 ,  0.8651769 ,  0.24529557,
          0.6088559 , -0.08106995, -0.6349347 ,  0.52693254,  0.28947884,
          0.0616026 ]], dtype=float32),
 array([ 0.0829579 ,  0.42482492, -0.17379153,  0.05150287,  0.25609   ,
         0.03114478,  0.0452861 ,  0.26177484,  0.10652176,  0.74473584,
         0.40275684], dtype=float32)]

In [97]:
y_log=model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [98]:
y_pred=np.where(y_log>0.5,1,0)

In [99]:
accuracy_score(y_test,y_pred)

0.8535